ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS comments TEXT,
  ADD COLUMN IF NOT EXISTS keywords TEXT,
  ADD COLUMN IF NOT EXISTS username TEXT,
  ADD COLUMN IF NOT EXISTS min INTEGER,
  ADD COLUMN IF NOT EXISTS max INTEGER,
  ADD COLUMN IF NOT EXISTS posts INTEGER,
  ADD COLUMN IF NOT EXISTS old_posts INTEGER,
  ADD COLUMN IF NOT EXISTS delay INTEGER,
  ADD COLUMN IF NOT EXISTS expiry TEXT;
